### ISSUE TITLE
Error in Semantic Networks code

### ISSUE THREAD

**Issue by gorkang** [mkearney/rstudioconf_tweets#1]
When running your Rmd, I find the following error in lines 232-239:

```
## iterate by row
row_dfs <- lapply(
  seq_len(nrow(rt)), function(i)
    unlist_df(from_screen_name = rt$screen_name[i],
      reply = rt$reply_to_screen_name[i],
      mention = rt$mentions_screen_name[i],
      quote = rt$quoted_screen_name[i],
      retweet = rt$retweet_screen_name[i])
)

```

> Unknown or uninitialised column: 'quoted_screen_name'.Unknown or uninitialised column: 'retweet_screen_name'.Error: Columns `quote`, `retweet` must be 1d atomic vectors or lists

Thanks for the awesome code!

**Comment by mkearney** [comment]
This should be fixed in the newest version of rtweet. Off the top of my head, I thought I added those variables before the last CRAN release. I could be wrong, in which case you'd need to install the github version of rtweet.

**Comment by gorkang** [comment]
Installing the dev version of rtweet solved it. Thanks!
